version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:457656920339:task-definition/hello-world-rest-api:3"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"