version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - IMAGE_URI=${REPOSITORY_URI}:${TAG}
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo Pushing docker image
    - mvn compile jib:build
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json